[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vesting = "4iC229Bhe8AH7KYQqQTyiZX7fhY3buzX6upoS8Rfyk96"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait=100000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
