[package]
name = "stake-mollusk-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
mollusk-svm = "0.5.1"
solana-account = "2.2.1"
solana-precompiles = "2.2.2"
solana-program = "3.0.0"
solana-pubkey = "2.4.0"
solana-sdk = "2.3.1"
