[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_intro = "CUkzBSEdfAxfCLH1kAXLdjWhtcWRyf89ExsukP3VSgCZ"

# [programs.devnet]
# anchor_intro="CUkzBSEdfAxfCLH1kAXLdjWhtcWRyf89ExsukP3VSgCZ"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait=10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
